stages:
  - deploy
  
variables:
  AWS_DEFAULT_REGION: $S3_BUCKET_REGION
  BUCKET_NAME: $S3_BUCKET_NAME


deploy:
  image: "python:latest" 
  stage: deploy
  script:
    - aws s3 cp index.html s3://www.rahulr.me